### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-germany#19]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] l10n_de_country_states - By @chienandalu - #21
- [x] l10n_de_location_nuts - By @chienandalu - #22  
- [x] l10n_de_steuernummer - By @pedrobaeza - #23
