### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-germany#26]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] l10n_de_country_states - By @rami-wafaie - #29 
- [x] l10n_de_location_nuts - By @rami-wafaie - #30 
- [x] l10n_de_steuernummer - By @rami-wafaie - #31

**Comment by pedrobaeza** [comment]
Everything migrate, so closing
